### ISSUE TITLE
support compose

### ISSUE THREAD

**Issue by ber4444** [JakeWharton/okhttp-idling-resource#23]
Could you also support `androidx.compose.ui.test.IdlingResource`?

**Comment by JakeWharton** [comment]
Hi! Unfortunately in the years since creating this library I have become staunchly anti-`IdlingResource`. The right way to write tests which are stable is to react and/or wait for changes to appear on screen before performing subsequent actions.

So, for example, if you want to sign in to an app you would enter email text, enter password text, and then click a button like normal. But then, instead of having an `IdlingResource` which is waiting on the background thread performing the network call, you simply wait for the next expected UI with a timeout (such as the presence of a "Home" title on a toolbar or whatever is appropriate for your app). How the app actually performed that background work to authenticate you is irrelevant and `IdlingResource`s play whack-a-mole with async work.

As such, I won't be maintaining this library anymore and will not be adding new functionality to it. Google is wrong for pushing `IdlingResource` as a continued solution.
